# Generated by Django 4.0.2 on 2022-03-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('category_num', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='enter category name', max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_num', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='enter product name', max_length=50, verbose_name='product name')),
                ('product_price', models.FloatField()),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bill_num', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='enter customer name', max_length=5, verbose_name='custome name')),
                ('total_sum', models.FloatField()),
                ('products', models.ManyToManyField(to='hello.product')),
            ],
        ),
    ]
